version: '3.8'

services:
  # --- หลังบ้าน (Backend) ---
  backend-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: scanner-backend
    ports:
      - "8000:8000"
    restart: always

  # --- หน้าบ้าน (Frontend) ---
  frontend-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scanner-frontend
    ports:
      - "5173:5173" # ปรับให้ตรงกับที่แอปคุณใช้
    restart: always
    depends_on:
      - backend-api