SID_MAP = {
    "*S-1-1-0": "Everyone",
    "*S-1-5-9": "Enterprise Domain Controllers",
    "*S-1-5-11": "Authenticated Users",
    "*S-1-5-32-544": "Administrators",
    "*S-1-5-32-545": "Users",
    "*S-1-5-32-546": "Guests",
    "*S-1-5-32-551": "Backup Operators",
    "*S-1-5-32-555": "Remote Desktop Users",
    "*S-1-5-19": "Local Service",
    "*S-1-5-20": "Network Service",
    "*S-1-5-6": "Service",
    "*S-1-5-90-0": "Window Manager",
    "*S-1-5-113": "NT AUTHORITY\\Local Account",
    "*S-1-5-114": "NT AUTHORITY\\Local Account and member of Administrators group",
}

USER_RIGHTS_MAP = {
    "Access Credential Manager as a trusted caller": "SeTrustedCredManAccessPrivilege",
    "Access this computer from the network": "SeNetworkLogonRight",
    "Act as part of the operating system": "SeTcbPrivilege",
    "Allow log on locally": "SeInteractiveLogonRight",
    "Allow log on through Remote Desktop Services": "SeRemoteInteractiveLogonRight",
    "Back up files and directories": "SeBackupPrivilege",
    "Bypass traverse checking": "SeChangeNotifyPrivilege",
    "Change the system time": "SeSystemtimePrivilege",
    "Create a pagefile": "SeCreatePagefilePrivilege",
    "Create a token object": "SeCreateTokenPrivilege",
    "Create global objects": "SeCreateGlobalPrivilege",
    "Create permanent shared objects": "SeCreatePermanentPrivilege",
    "Create symbolic links": "SeCreateSymbolicLinkPrivilege",
    "Debug programs": "SeDebugPrivilege",
    "Deny access to this computer from the network": "SeDenyNetworkLogonRight",
    "Deny log on as a batch job": "SeDenyBatchLogonRight",
    "Deny log on as a service": "SeDenyServiceLogonRight",
    "Deny log on locally": "SeDenyInteractiveLogonRight",
    "Deny log on through Remote Desktop Services": "SeDenyRemoteInteractiveLogonRight",
    "Enable computer and user accounts to be trusted for delegation": "SeEnableDelegationPrivilege",
    "Force shutdown from a remote system": "SeRemoteShutdownPrivilege",
    "Generate security audits": "SeAuditPrivilege",
    "Impersonate a client after authentication": "SeImpersonatePrivilege",
    "Increase scheduling priority": "SeIncreaseBasePriorityPrivilege",
    "Load and unload device drivers": "SeLoadDriverPrivilege",
    "Lock pages in memory": "SeLockMemoryPrivilege",
    "Log on as a batch job": "SeBatchLogonRight",
    "Log on as a service": "SeServiceLogonRight",
    "Manage auditing and security log": "SeSecurityPrivilege",
    "Modify firmware environment values": "SeSystemEnvironmentPrivilege",
    "Modify an object label": "SeRelabelPrivilege",
    "Perform volume maintenance tasks": "SeManageVolumePrivilege",
    "Profile single process": "SeProfileSingleProcessPrivilege",
    "Profile system performance": "SeSystemProfilePrivilege",
    "Replace a process level token": "SeAssignPrimaryTokenPrivilege",
    "Restore files and directories": "SeRestorePrivilege",
    "Shut down the system": "SeShutdownPrivilege",
    "Take ownership of files or other objects": "SeTakeOwnershipPrivilege",
}

SPECIAL_VALUE_MAP = {
    "send ntlmv2 response only. refuse lm & ntlm": "5",
    "negotiate signing": "1",
    "require ntlmv2 session security and require 128-bit encryption": "537395200",
    "lock workstation": "1",
    "prompt for consent on the secure desktop": "5",
    "prompt for credentials on secure desktop": "1",
    "automatically deny elevation requests": "3",
    "admin approval mode with enhanced privilege protection": "2",
    "no one (blank)": "",
    "block": "block",

        # ── Windows Server 2025 (new) ────────────────────────────────────────
    # LAN Manager auth level — wording ต่างจาก Win11 (comma แทน period, "Responses" แทน "Response")
    "send ntlmv2 responses only, refuse lm and ntlm": "5",
    # NTLMMinClientSec / NTLMMinServerSec — wording ต่างจาก Win11 ("128bit" ไม่มี hyphen)
    "require ntlmv2 session security, require 128bit encryption": "537395200",
    # RestrictSendingNTLMTraffic: 1 = Audit all
    "audit all": "1",
    # AuditReceivingNTLMTraffic: 2 = Enable auditing for all accounts
    "enable auditing for all accounts": "2",
    "p-node (recommended)": "2",
    "highest protection, source routing is completely disabled": "2",
    "block all": "0",
    "authenticated": "1",
    "do not execute any autorun commands": "1",
    "all drives": "255",
    "use tls 1.1 and tls 1.2": "2560",
    "disable java": "0",
    "high safety": "65536",
    "prompt": "1",
    "anonymous logon": "0",
    "high level": "3",
    "on, but disallow access above lock": "1",
}

FIREWALL_PROFILE_MAP = {
    "Domain Profile": "domain",
    "Private Profile": "private",
    "Public Profile": "public",
}

FIREWALL_SETTING_MAP = {
    "Firewall State": ("state", None),
    "Inbound Connections": ("firewallpolicy", "inbound"),
    "Outbound Connections": ("firewallpolicy", "outbound"),
    "Display a notification": ("settings", "inboundusernotification"),
    "Apply local firewall rules": ("settings", "localfirewallrules"),
    "Apply local connection security rules": ("settings", "localconsecrules"),
    "Size limit": ("logging", "maxfilesize"),
    "Log dropped packets": ("logging", "droppedpackets"),
    "Log successful connections": ("logging", "allowedconnections"),
}

SECEDIT_KEY_MAP = {
    "Minimum password length": "MinimumPasswordLength",
    "Maximum password age": "MaximumPasswordAge",
    "Minimum password age": "MinimumPasswordAge",
    "Enforce password history": "PasswordHistorySize",
    "Password must meet complexity requirements": "PasswordComplexity",
    "Store passwords using reversible encryption": "ClearTextPassword",
    "Account lockout duration": "LockoutDuration",
    "Account lockout threshold": "LockoutBadCount",
    "Reset account lockout counter after": "ResetLockoutCount",
    "Allow Administrator account lockout": "AllowAdministratorLockout",
}

AUDIT_SUBCATEGORY_MAP = {
    "Audit Credential Validation": "Credential Validation",
    "Audit Kerberos Authentication Service": "Kerberos Authentication Service",
    "Audit Kerberos Service Ticket Operations": "Kerberos Service Ticket Operations",
    "Audit Security Group Management": "Security Group Management",
    "Audit User Account Management": "User Account Management",
    "Audit Computer Account Management": "Computer Account Management",
    "Audit Distribution Group Management": "Distribution Group Management",
    "Audit Other Account Management Events": "Other Account Management Events",
    "Audit PNP Activity": "Plug and Play Events",
    "Audit Process Creation": "Process Creation",
    "Audit Process Termination": "Process Termination",
    "Audit Account Lockout": "Account Lockout",
    "Audit Group Membership": "Group Membership",
    "Audit Logon": "Logon",
    "Audit Logoff": "Logoff",
    "Audit Other Logon/Logoff Events": "Other Logon/Logoff Events",
    "Audit Special Logon": "Special Logon",
    "Audit Network Policy Server": "Network Policy Server",
    "Audit Detailed File Share": "Detailed File Share",
    "Audit File Share": "File Share",
    "Audit File System": "File System",
    "Audit Other Object Access Events": "Other Object Access Events",
    "Audit Registry": "Registry",
    "Audit Removable Storage": "Removable Storage",
    "Audit SAM": "SAM",
    "Audit Audit Policy Change": "Audit Policy Change",
    "Audit Authentication Policy Change": "Authentication Policy Change",
    "Audit MPSSVC Rule-Level Policy Change": "MPSSVC Rule-Level Policy Change",
    "Audit Other Policy Change Events": "Other Policy Change Events",
    "Audit Authorization Policy Change": "Authorization Policy Change",
    "Audit Sensitive Privilege Use": "Sensitive Privilege Use",
    "Audit Non Sensitive Privilege Use": "Non Sensitive Privilege Use",
    "Audit Other System Events": "Other System Events",
    "Audit Security State Change": "Security State Change",
    "Audit Security System Extension": "Security System Extension",
    "Audit System Integrity": "System Integrity",
}
