name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Deploy Script
        env:
          WINRM_USER: ${{ secrets.WINRM_USER }}
          WINRM_PASS: ${{ secrets.WINRM_PASS }}
        run: powershell -File deploy.ps1