name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Deploy Script
        env:
          AGENT_INSTALL_TOKEN: ${{ secrets.AGENT_INSTALL_TOKEN }}
          WINRM_USER: ${{ secrets.WINRM_USER }}
          WINRM_PASS: ${{ secrets.WINRM_PASS }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL: ${{ secrets.GROQ_MODEL }}
        run: powershell -File deploy.ps1
